'use client';
// /app/layout.js

import { Inter } from 'next/font/google';
import './globals.css';
import { AuthContextProvider } from '@/context/AuthContext';
import { usePathname } from 'next/navigation';
const inter = Inter({ subsets: ['latin'] });
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import BottomNavbar from '@/components/Layout/BottomNavbar';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${inter.className} relative md:m-auto md:w-96`}>
        <AuthContextProvider>{children}</AuthContextProvider>
        {pathname === '/login' ? null : <BottomNavbar />}
        <ToastContainer />
      </body>
    </html>
  );
}
