// /app/layout.js

import { Inter } from 'next/font/google';
import './globals.css';
import { AuthContextProvider } from '@/context/AuthContext';

const inter = Inter({ subsets: ['latin'] });
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import BottomNavbar from '@/components/Layout/BottomNavbar';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative dark:bg-slate-800`}>
        <AuthContextProvider>{children}</AuthContextProvider>
        <BottomNavbar />
        <ToastContainer />
      </body>
    </html>
  );
}
